### ISSUE TITLE
Plotting throws `DuplicateNameException` when category has a channel

### ISSUE THREAD

**Issue by dsavoiu** [uhh-cms/columnflow#156]
Ran into this error in the mttbar analysis. An `order.unique.DuplicateNameException` is thrown when plotting, which is unexpected. It seems some `order` objects like `Category` are being copied when passed to the plotting function. The copy logic is adding the copies to the parent channel, which triggers the exception:

```
Traceback (most recent call last):
  ...
  File "modules/columnflow/columnflow/tasks/plotting.py", line 155, in run
    category_inst=category_inst.copy(),
  File "modules/columnflow/modules/order/order/category.py", line 181, in copy
    inst.channel.categories.add(inst)
  File "modules/columnflow/modules/order/order/unique.py", line 231, in add
    raise DuplicateNameException(self.cls, obj.name)
order.unique.DuplicateNameException: duplicate 'order.category.Category' object with name '1e' encountered
```

The category `1e` is defined as belonging to the channel electron channel `e`.
```
config.add_category(
    name="1e",
    id=2,
    selection="sel_1e",
    label="1e",
    channel=config.get_channel("e"),
)
```

A quick fix would be to add `channel=None` to the copy command [here](https://github.com/uhh-cms/columnflow/blob/ae66dab995c17aa8be24cb26986cf2bd4ef9c35f/columnflow/tasks/plotting.py#L155), but if the channel information is needed for plotting at some point in the future one might need to find a better way.

**Comment by riga** [comment]
Indeed...

@mafrahm and I were hoping that there were no side effects when creating the copies, so that they can be used as containers to carry custom plot options per category, process, etc.

However, seeing the issue above (and also revisiting the overhead again), we should come up with a better solution.

**Comment by mafrahm** [comment]
Is this a problem that is only related to categories or are there similar problems with the variable and process insts aswell? The category_inst copies are barely used anyway at the moment (only to read out the category label), but with variables and processes, we actually change large parts of the insts as part of the plotting based on the given input parameters.
