### ISSUE TITLE
Handling arrays with zero rows/entries

### ISSUE THREAD

**Issue by dsavoiu** [uhh-cms/columnflow#161]
The array reduction performed during `cf.ReduceEvents` may result in an empty set of selected events. In the current implementation (revision [8b41c5](https://github.com/uhh-cms/columnflow/tree/8b41c5a13686fd6c539d2848f79780b1c8b50840)), this results in an error when writing to Parquet. The problem arises because the separation of an array into chunks yields an empty list if the array has zero entries:
```
Traceback (most recent call last):
  ...
  File "modules/columnflow/columnflow/tasks/production.py", line 117, in run
    law.pyarrow.merge_parquet_task(self, sorted_chunks, output, local=True)
  File "modules/columnflow/modules/law/law/contrib/pyarrow/util.py", line 132, in merge_parquet_task
    merge(inputs, output)
  File "modules/columnflow/modules/law/law/contrib/pyarrow/util.py", line 115, in merge
    merge_parquet_files(
  File "modules/columnflow/modules/law/law/contrib/pyarrow/util.py", line 35, in merge_parquet_files
    raise Exception("cannot merge empty list of parquet files")
Exception: cannot merge empty list of parquet files
```

For some tighter selections, having zero-length arrays after `ReduceEvents` can happen occasionally, so it would make sense to support this use case in the long run.

The most straightforward way would be to simply write the zero-length array to Parquet, making sure that column/schema information is preserved. Until recently, reading such empty arrays from Parquet was not implemented in Awkward but this has been added starting with version [2.0.7](https://github.com/scikit-hep/awkward/releases/tag/v2.0.7).

Such an implementation would also require either short-circuiting the chunked processing and writing out the empty array directly, or otherwise adapting the chunking logic to always produce at least one chunk, which would be empty in the zero-length case.

There also remain some limitations when handling zero-length arrays with Awkward + Arrow/Parquet (in particular regarding nullability for nested/ragged columns), for which workarounds would be needed.

An alternative option would be to produce no output file for zero-length arrays, but this would probably interfere with the workflow management, which relies on the presence of output files to check task completion.

**Comment by riga** [comment]
This might also relate to a different issue that currently pops up with awkward 2.0.7, e.g.

```
TypeError: while calling

    ak.to_layout(
        array = numpy.ndarray([None None None ... 201.0 None None])
        allow_record = False
        allow_other = False
        regulararray = False
    )

Error details: Awkward Array does not support arrays with object dtypes.
```

in code that was previously working :/ Unfortunately, awkward is known for adding breaking changes between patch versions.

I'm looking into this today.

**Comment by riga** [comment]
Ok, turns out this was a different issue related to the handling of None's which cannot be used anymore in `where` statements. One can use `nan` and `ak.nan_to_none` though to obtain the same outcome ;)
