### ISSUE TITLE
Cutflow-related tasks do not work for data

### ISSUE THREAD

**Issue by dsavoiu** [uhh-cms/columnflow#203]
When running on data, the `PlotCutflow` and `PlotCutflowVariables` tasks and their upstream dependencies run into issues.

For example, the `MergeSelectionMasks` task complains about the sum of MC weights not being found.

```
Traceback (most recent call last):
  File "data/software/venvs/venv_columnar_dev/lib/python3.9/site-packages/luigi/worker.py", line 203, in run
    new_deps = self._run_get_new_deps()
  File "data/software/venvs/venv_columnar_dev/lib/python3.9/site-packages/luigi/worker.py", line 147, in _run_get_new_deps
    requires = next(task_gen)
  File "modules/columnflow/modules/law/law/contrib/tasks/__init__.py", line 555, in run
    self.merge(inputs, self.output())
  File "modules/columnflow/columnflow/tasks/selection.py", line 354, in merge
    inputs = self.zip_results_and_columns(inputs, tmp_dir)
  File "modules/columnflow/columnflow/tasks/selection.py", line 365, in zip_results_and_columns
    self.norm_weight_producer.run_setup(
  File "modules/columnflow/columnflow/columnar_util.py", line 1889, in run_setup
    self.setup_func(reqs, inputs)
  File "modules/columnflow/columnflow/production/normalization.py", line 94, in normalization_weights_setup
    for process_id, sum_weights in selection_stats["sum_mc_weight_per_process"].items():
KeyError: 'sum_mc_weight_per_process'
```

The task expects to find the key `sum_mc_weight_per_process` in the `stats` output of `SelectEvents`, but this information is not available for data. Another related issue is that the current implementation of `PlotCutflow` relies on the histogram of `mc_weight`, but this quantity is not produced in data (the corresponding producer is marked `mc_only`).

I think a good way to solve both issues would be to replace `mc_weight` consistently with a generalized `weight` variable, which would be `1.0` for data and the usual generator weight for MC. Then one could make use of the fact that `data` is its own process and store the sum of this generalized `weight` column (i.e. the raw event count) under `sum_weight_per_process` alongside the other MC weights. In this way, both `MergeSelectionMasks` and the cutflow tasks that rely on a histogram of `weight` should work transparently.

**Comment by riga** [comment]
Good that you caught that one! I think the cutflow pipeline is (hopefully) the last remaining bit that still has some MC taste to it.

> I think a good way to solve both issues would be to replace mc_weight consistently with a generalized weight variable, which would be 1.0 for data and the usual generator weight for MC.

I Think so too and opened #206 for that :)
